[package]
name = "retry_future"
version = "0.1.0"
authors = ["Evan Cameron <cameron.evan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["full"], optional = true }
tokio-test = { version = "0.2", optional = true }
async-std = { version = "1.7", optional = true }


[features]
default = ["tokio-runtime"]
tokio-runtime = ["tokio", "tokio-test"]
async-runtime = ["async-std"]

