unstable_features = true
imports_granularity = "Crate"
merge_derives = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
format_code_in_doc_comments = true
normalize_comments = true
